### ISSUE TITLE
First run will promote things based on their initial import date

### ISSUE THREAD

**Issue by jc0b** [jc0b/munki-promoter#4]
Items that are eligible for promotion, but haven't yet had a promotion run against them (and are thus lacking metadata about when they were last promoted by `munki-promoter`), will be promoted by `munki-promoter` earlier than expected.

Once this issue occurs once, it will not occur again.

The logic for detecting this seems like it would be hard to implement for a variety of cases - the proposal is to provide a command-line flag that allows working around this issue temporarily. Other command-line flags should be provided that will allow setting/resetting the "last edited dates" for all items/items that are missing them.

**Comment by kaiobendrauf** [comment]
Fixed in 159e54d, documentation still required and should be added to the README/getting started docs.

**Comment by jc0b** [comment]
Docs done
